### ISSUE TITLE
Planner.launch file missing

### ISSUE THREAD

**Issue by gsakshata** [MichalDobis/osm_planner#2]
Launch file - simulation.launch calls planner.launch file. But the planner file doesn't exists.

**Comment by MichalDobis** [comment]
Launch file simulation.launch is outdated. Package has been rebuilt as move_group plugin for nav_core/base_global_planner. So if you want launch the package you should launch move_group.launch https://github.com/MichalDobis/osm_planner/blob/gps_compass_correction/launch/move_base.launch

After launch you can draw parsed map by rosservice call /move_base/Planner/draw_route and in Rviz you can set 2D Nav goal
